// src/components/Contact.vue
<script setup>
import { ref } from 'vue'
import { CloseBold } from '@element-plus/icons-vue'
import { useLanguageStore } from '@/stores'

const languageStore = useLanguageStore()

const inputName = ref('')
const inputEmail = ref('')
const inputMessage = ref('')
</script>

<template>
  <div class="contact">
    <div class="contact_title">{{ languageStore.text.contactTitle }}</div>
    <div class="contact_sub_title">
      {{ languageStore.text.contactSubTitle }}
    </div>
    <div class="contact_content">
      <el-input
        class="input_name"
        v-model="inputName"
        :placeholder="languageStore.text.contactNamePlaceholder"
        clearable
        :clear-icon="CloseBold"
      />
      <el-input
        class="input_email"
        v-model="inputEmail"
        :placeholder="languageStore.text.contactEmailPlaceholder"
        clearable
        :clear-icon="CloseBold"
      />
      <el-input
        class="input_message"
        v-model="inputMessage"
        :rows="5"
        type="textarea"
        :placeholder="languageStore.text.contactMessagePlaceholder"
        clearable
        :clear-icon="CloseBold"
      />
    </div>
    <div class="submit_button">
      <el-button type="primary">{{ languageStore.text.submit }}</el-button>
    </div>
  </div>
</template>
<style scoped lang="scss">
.contact {
  margin-bottom: 10vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  .contact_title {
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 5rem;
    font-weight: bold;
    color: var(--my-contact_title);
    margin-top: 10vh;
  }
  .contact_sub_title {
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 1.2rem;
    color: var(--my-contact_sub_title);
    margin-top: 1vh;
  }
  .contact_content {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    margin-top: 5vh;

    .el-input {
      height: 7vh;
      width: 45vw;
      font-size: 1rem;
      --el-input-focus-border-color: var(--my-input_focus_border);
    }
    .el-textarea {
      font-size: 1rem;
      --el-input-focus-border-color: var(--my-input_focus_border);
    }
    .input_email,
    .input_message {
      margin-top: 2vh;
    }
  }
  .submit_button {
    margin-top: 5vh;

    .el-button {
      width: 10vw;
      height: 5vh;
      font-size: 1rem;
      --el-button-active-bg-color: var(--my-button_active_bg);
      --el-button-active-border-color: var(--my-button_active_border);
      --el-button-hover-border-color: var(--my-button_hover_bg);
      --el-button-hover-bg-color: var(--my-button_hover_border);
    }
  }
}
</style>

// shannyDev-react/src/components/Contact/Contact.tsx
import { useState } from 'react'
import { Input, Button } from 'antd'
import { CloseOutlined } from '@ant-design/icons'
import { useLanguageStore } from '@/stores'
import './Contact.scss'

const { TextArea } = Input

interface ContactProps {
  id?: string
}

const Contact = ({ id }: ContactProps) => {
  const text = useLanguageStore((state) => state.text())

  const [inputName, setInputName] = useState('')
  const [inputEmail, setInputEmail] = useState('')
  const [inputMessage, setInputMessage] = useState('')

  return (
    <div className="contact" id={id}>
      <div className="contact_title">{text.contactTitle}</div>
      <div className="contact_sub_title">{text.contactSubTitle}</div>
      <div className="contact_content">
        <Input
          className="input_name"
          value={inputName}
          onChange={(e) => setInputName(e.target.value)}
          placeholder={text.contactNamePlaceholder}
          allowClear={{ clearIcon: <CloseOutlined /> }}
        />
        <Input
          className="input_email"
          value={inputEmail}
          onChange={(e) => setInputEmail(e.target.value)}
          placeholder={text.contactEmailPlaceholder}
          allowClear={{ clearIcon: <CloseOutlined /> }}
        />
        <TextArea
          className="input_message"
          value={inputMessage}
          onChange={(e) => setInputMessage(e.target.value)}
          rows={5}
          placeholder={text.contactMessagePlaceholder}
          allowClear={{ clearIcon: <CloseOutlined /> }}
        />
      </div>
      <div className="submit_button">
        <Button type="primary">{text.submit}</Button>
      </div>
    </div>
  )
}

export default Contact
