// shannyDev-react/src/App.tsx
import { useEffect } from 'react'
import { Layout } from 'antd'
import Header from '@/components/Header/Header'
import About from '@/components/About/About'
import Resume from '@/components/Resume/Resume'
import Project from '@/components/Project/Project'
import Contact from '@/components/Contact/Contact'
import { useHeaderStore } from '@/stores'
import './App.scss'

const { Header: AntHeader, Content } = Layout

const MainLayout = () => {
  const anchorList = useHeaderStore((state) => state.anchorList)
  const setHeaderActive = useHeaderStore((state) => state.setHeaderActive)

  const handleScroll = () => {
    const scrollTop = window.scrollY
    const clientHeight = document.documentElement.clientHeight
    const pageHeight = document.documentElement.scrollHeight
    const list = anchorList

    if (scrollTop + clientHeight >= pageHeight - 50) {
      setHeaderActive(list.length - 1)
      return
    }

    let current = 0
    for (let i = 0; i < list.length; i++) {
      const el = document.getElementById(list[i])
      if (!el) continue

      const rect = el.getBoundingClientRect()
      if (rect.top <= 200) {
        current = i
      }
    }

    setHeaderActive(current)
  }

  useEffect(() => {
    window.addEventListener('scroll', handleScroll)
    // handleScroll()
    return () => {
      window.removeEventListener('scroll', handleScroll)
    }
  }, [anchorList, setHeaderActive])

  return (
    <div className="common-layout">
      <Layout>
        <AntHeader className="header">
          <Header />
        </AntHeader>
        <Content className="main">
          <About />
          <Resume id="resume" />
          <Project id="project" />
          <Contact id="contact" />
        </Content>
      </Layout>
    </div>
  )
}

export default MainLayout

// shannyDev-vue/src/App.vue
<script setup>
import { onMounted, onUnmounted } from 'vue'

import Header from '@/components/Header/Header.vue'
import About from '@/components/About.vue'
import Resume from '@/components/Resume.vue'
import Project from '@/components/Project.vue'
import Contact from '@/components/Contact.vue'

import { useHeaderStore } from '@/stores'
const headerStore = useHeaderStore()

const handleScroll = () => {
  const scrollTop = window.scrollY
  const clientHeight = document.documentElement.clientHeight
  const pageHeight = document.documentElement.scrollHeight
  const list = headerStore.anchorList

  if (scrollTop + clientHeight >= pageHeight - 50) {
    headerStore.headerActive = list.length - 1
    return
  }

  let current = 0
  for (let i = 0; i < list.length; i++) {
    const el = document.getElementById(list[i])
    if (!el) continue

    const rect = el.getBoundingClientRect()
    if (rect.top <= 200) {
      current = i
    }
  }

  headerStore.headerActive = current
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
  handleScroll()
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})
</script>

<template>
  <div class="common-layout">
    <el-container>
      <el-header class="header">
        <Header />
      </el-header>
      <el-main class="main">
        <About />
        <Resume id="resume" />
        <Project id="project" />
        <Contact id="contact" />
      </el-main>
    </el-container>
  </div>
</template>
<style scoped lang="scss">
.header {
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
  width: 100%;
  padding: 0;
  --el-header-height: 6vh;

  > div {
    width: 100% !important;
  }
}
.main {
  overflow: visible;
}
</style>
