// shannyDev-vue/src/views/Header.vue
<script setup>
import Link from '@/components/Link.vue'
import { Sunny, Moon } from '@element-plus/icons-vue'
import { useHeaderStore, useLanguageStore } from '../stores/'
const headerStore = useHeaderStore()
const languageStore = useLanguageStore()
</script>

<template>
  <el-affix :offset="0">
    <div class="header-group">
      <div class="header_left">
        <Link
          :active="0"
          href="https://www.shanny.wang"
          text="www.shanny.wang"
          position="left"
          :clickFunction="() => headerStore.changeHeader(0)"
        />
      </div>
      <div class="header_center">
        <Link
          href="#about"
          :active="0"
          :text="languageStore.text.about"
          :clickFunction="() => headerStore.changeHeader(0)"
        />
        <Link
          href="#resume"
          :active="1"
          :text="languageStore.text.resume"
          :clickFunction="() => headerStore.changeHeader(1)"
        />
        <Link
          href="#project"
          :active="2"
          :text="languageStore.text.project"
          :clickFunction="() => headerStore.changeHeader(2)"
        />
        <Link
          href="#contact"
          :active="3"
          :text="languageStore.text.contact"
          :clickFunction="() => headerStore.changeHeader(3)"
        />
      </div>
      <div class="header_right">
        <Link
          href="https://www.shanny.wang/react"
          text="To React"
          position="right"
          target="_blank"
        />
        <Link
          :text="languageStore.lang === 'zh-cn' ? '中' : 'EN'"
          position="right"
          :clickFunction="languageStore.toggleLang"
        />
        <!-- <Link
          :isIcon="true"
          :icon="state === 'dark' ? Moon : Sunny"
          position="right"
          :clickFunction="headerStore.toggleTheme"
        /> -->
      </div>
    </div>
  </el-affix>
</template>
<style scoped lang="scss">
.header-group {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: var(--my-header_bg);
  border-bottom: 0.1rem solid var(--my-header_border_bottom);
  width: 100vw;
  height: 6vh;
}
</style>

// shannyDev-react/src/pages/Header/Header.tsx
import { Affix } from 'antd'
import LinkComponent from '@/components/Link/Link'
import { useHeaderStore, useLanguageStore } from '@/stores'
import styles from './Header.module.scss'

const Header = () => {
  const { changeHeader } = useHeaderStore()
  const languageStore = useLanguageStore()
  const text = languageStore.text()

  return (
    <Affix offsetTop={0} style={{ width: '100%' }}>
      <div className={styles['header-group']}>
        <div className={styles['header_left']}>
          <LinkComponent
            active={0}
            href="https://www.shanny.wang/react"
            text="www.shanny.wang / React"
            position="left"
            clickFunction={() => changeHeader(0)}
          />
        </div>
        <div className={styles['header_center']}>
          <LinkComponent
            href="#about"
            active={0}
            text={text.about}
            clickFunction={() => changeHeader(0)}
          />
          <LinkComponent
            href="#resume"
            active={1}
            text={text.resume}
            clickFunction={() => changeHeader(1)}
          />
          <LinkComponent
            href="#project"
            active={2}
            text={text.project}
            clickFunction={() => changeHeader(2)}
          />
          <LinkComponent
            href="#contact"
            active={3}
            text={text.contact}
            clickFunction={() => changeHeader(3)}
          />
        </div>
        <div className={styles['header_right']}>
          <LinkComponent
            href="https://www.shanny.wang"
            text="To Vue"
            position="right"
            target="_blank"
          />
          <LinkComponent
            text={languageStore.lang === 'zh-cn' ? '中' : 'EN'}
            position="right"
            clickFunction={languageStore.toggleLang}
          />
        </div>
      </div>
    </Affix>
  )
}

export default Header
