// shannyDev-vue/src/components/About.vue
<script setup>
import { useLanguageStore } from '@/stores'
const languageStore = useLanguageStore()
</script>

<template>
  <div class="about">
    <div class="about_top">
      <div class="about_name">
        <div>{{ languageStore.text.aboutTitleOne }}</div>
        <div>{{ languageStore.text.aboutTitleTwo }}</div>
      </div>
      <div class="about_msg">
        {{ languageStore.text.aboutContentOne }}
        <span class="about_lan">&nbsp;Vue3&nbsp;</span>
        {{ languageStore.text.aboutContentTwo }}
        {{ languageStore.text.aboutContentThree }}
        <span class="about_lan">&nbsp;.NET、Java&nbsp;</span>
        {{ languageStore.text.aboutContentFour }}
        {{ languageStore.text.aboutContentFive }}
      </div>
    </div>
    <div class="about_expertise" id="about">
      <div class="ex_title">
        {{ languageStore.text.exTitle }}
      </div>

      <div class="ex_content">
        <div class="content_header">
          {{ languageStore.text.exContentHeader }}
        </div>
        <div class="content_list">
          <div class="content">
            <div class="content_title one">
              {{ languageStore.text.exContentTitleOne }}
            </div>
            <div class="content_msg">
              <div class="text_h3">&lt;h3&gt;</div>
              <div class="msg">
                {{ languageStore.text.exContentMsgOne }}
              </div>
              <div class="text_h3">&lt;h3/&gt;</div>
            </div>
          </div>
          <div class="content">
            <div class="content_title two">
              {{ languageStore.text.exContentTitleTwo }}
            </div>
            <div class="content_msg">
              <div class="text_h3">&lt;h3&gt;</div>
              <div class="msg">
                {{ languageStore.text.exContentMsgTwo }}
              </div>
              <div class="text_h3">&lt;h3/&gt;</div>
            </div>
          </div>
          <div class="content">
            <div class="content_title three">
              {{ languageStore.text.exContentTitleThree }}
            </div>
            <div class="content_msg">
              <div class="text_h3">&lt;h3&gt;</div>
              <div class="msg">
                {{ languageStore.text.exContentMsgThree }}
              </div>
              <div class="text_h3">&lt;h3/&gt;</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<style scoped lang="scss">
.about {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;

  .about_top {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 92vh;

    .about_name {
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      font-size: 5rem;
      color: var(--my-about_name);
      text-shadow: 0.25rem 0.25rem 0 var(--my-about_name_shadow);
    }

    .about_msg {
      display: flex;
      flex-direction: row;
      justify-content: center;
      align-items: center;
      font-size: 1.5rem;
      background-color: var(--my-about_msg_back);
      color: var(--my-about_msg);
      padding: 0.2rem 1rem;
      margin-top: 5vh;
      box-shadow: 0.3rem 0.3rem 0 var(--my-about_msg_shadow);

      .about_lan {
        color: var(--my-about_lan);
        font-weight: bold;
      }
    }
  }

  .about_expertise {
    width: 80vw;

    .ex_title {
      display: flex;
      justify-content: center;
      align-items: center;
      font-size: 5rem;
      font-weight: bold;
      color: var(--my-ex_title);
      margin-top: 10vh;
      text-shadow: 0.3rem 0.3rem 0 var(--my-ex_title_shadow);
    }

    .ex_content {
      display: flex;
      flex-direction: column;
      justify-content: start;
      align-items: center;
      border: 0.1rem solid var(--my-ex_content_border);
      margin-top: 5vh;

      .content_header {
        display: flex;
        justify-content: start;
        align-items: center;
        box-sizing: border-box;
        padding: 0 1rem;
        background-color: var(--my-ex_content_header_back);
        color: var(--my-ex_content_header);
        width: 100%;
        height: 8vh;
        font-size: 1.5rem;
      }
      .content_list {
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        background-color: var(--my-ex_content_list_back);
        width: 100%;

        .content {
          box-sizing: border-box;
          padding: 1rem;
          width: 33.33%;
          height: 45vh;

          .content_title {
            font-size: 4vh;
            position: relative;
            display: inline-block;
            z-index: 0;

            &::after {
              content: '';
              position: absolute;
              left: 0;
              bottom: 0.15vh;
              width: 100%;
              height: 1.2vh;
              z-index: -1;
            }
          }
          .content_title.one {
            &::after {
              background-color: var(--my-ex_underline_1);
            }
          }
          .content_title.two {
            &::after {
              background-color: var(--my-ex_underline_2);
            }
          }
          .content_title.three {
            &::after {
              background-color: var(--my-ex_underline_3);
            }
          }
          .content_msg {
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin: 1rem 0;
            height: 83%;

            .text_h3 {
              font-size: 2.5vh;
              color: var(--my-ex_text_h3);
              height: 15%;
            }
            .msg {
              display: flex;
              justify-content: start;
              align-items: center;
              border-left: 0.05rem solid var(--my-ex_content_msg_border);
              margin-left: 1.1vw;
              padding: 1rem 0 1rem 1rem;
              font-size: 3vh;
              line-height: 4vh;
              height: 90%;
            }
          }
        }
        .content:not(:last-child) {
          border-right: 0.1rem solid var(--my-ex_content_border);
        }
      }
    }
  }
}
</style>

// shannyDev-react/src/components/About/About.tsx
import { useLanguageStore } from '@/stores'
import './About.scss'
const About = () => {
  const text = useLanguageStore((state) => state.text())

  return (
    <div className="about">
      <div className="about_top">
        <div className="about_name">
          <div>{text.aboutTitleOne}</div>
          <div>{text.aboutTitleTwo}</div>
        </div>
        <div className="about_msg">
          {text.aboutContentOne}
          <span className="about_lan">&nbsp;Vue3&nbsp;</span>
          {text.aboutContentTwo}
          {text.aboutContentThree}
          <span className="about_lan">&nbsp;.NET、Java&nbsp;</span>
          {text.aboutContentFour}
          {text.aboutContentFive}
        </div>
      </div>

      <div className="about_expertise" id="about">
        <div className="ex_title">{text.exTitle}</div>

        <div className="ex_content">
          <div className="content_header">{text.exContentHeader}</div>
          <div className="content_list">
            {/* 第一项 */}
            <div className="content">
              <div className="content_title one">{text.exContentTitleOne}</div>
              <div className="content_msg">
                <div className="text_h3">&lt;h3&gt;</div>
                <div className="msg">{text.exContentMsgOne}</div>
                <div className="text_h3">&lt;h3/&gt;</div>
              </div>
            </div>

            {/* 第二项 */}
            <div className="content">
              <div className="content_title two">{text.exContentTitleTwo}</div>
              <div className="content_msg">
                <div className="text_h3">&lt;h3&gt;</div>
                <div className="msg">{text.exContentMsgTwo}</div>
                <div className="text_h3">&lt;h3/&gt;</div>
              </div>
            </div>

            {/* 第三项 */}
            <div className="content">
              <div className="content_title three">
                {text.exContentTitleThree}
              </div>
              <div className="content_msg">
                <div className="text_h3">&lt;h3&gt;</div>
                <div className="msg">{text.exContentMsgThree}</div>
                <div className="text_h3">&lt;h3/&gt;</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default About
