// shannyDev-react/src/pages/HeaderMobile/HeaderMobile.tsx
import { Affix, Drawer } from 'antd'
import LinkComponent from '@/components/Link/Link'
import { MenuOutlined } from '@ant-design/icons'
import { useHeaderStore, useLanguageStore } from '@/stores'
import styles from './HeaderMobile.module.scss'

const HeaderMobile = () => {
  const { drawer, setDrawer, changeHeader } = useHeaderStore()
  const languageStore = useLanguageStore()
  const text = languageStore.text()
  const { lang, toggleLang } = languageStore

  const closeDrawer = () => setDrawer(false)

  return (
    <Affix offsetTop={0} style={{ width: '100%' }}>
      <div className={styles['header-group']}>
        <div className={styles['header_left']}>
          <MenuOutlined
            className={styles.menu_icon}
            onClick={() => setDrawer(true)}
          />
          <Drawer
            open={drawer}
            placement="left"
            title=""
            closable={false}
            onClose={closeDrawer}
          >
            <LinkComponent
              href="#about"
              active={0}
              text={text.about}
              clickFunction={() => changeHeader(0)}
              isMobile
            />
            <LinkComponent
              href="#resume"
              active={1}
              text={text.resume}
              clickFunction={() => changeHeader(1)}
              isMobile
            />
            <LinkComponent
              href="#project"
              active={2}
              text={text.project}
              clickFunction={() => changeHeader(2)}
              isMobile
            />
            <LinkComponent
              href="#contact"
              active={3}
              text={text.contact}
              clickFunction={() => changeHeader(3)}
              isMobile
            />
          </Drawer>
        </div>
        <div className={styles['header_right']}>
          <LinkComponent
            href="https://www.shanny.wang"
            text="To Vue"
            position="right"
            target="_blank"
          />
          <LinkComponent
            text={lang === 'zh-cn' ? '中' : 'EN'}
            position="right"
            clickFunction={toggleLang}
            isMobile
          />
        </div>
      </div>
    </Affix>
  )
}

export default HeaderMobile

// shannyDev-vue/src/views/HeaderMobile.vue
<script setup>
import Link from '@/components/Link.vue'
import { Sunny, Moon, Menu } from '@element-plus/icons-vue'
import { useHeaderStore, useLanguageStore } from '../stores'
const headerStore = useHeaderStore()
const languageStore = useLanguageStore()
</script>

<template>
  <el-affix :offset="0">
    <div class="header-group">
      <div class="header_left">
        <el-icon @click="headerStore.drawer = true" class="menu_icon">
          <Menu />
        </el-icon>
        <el-drawer
          direction="ltr"
          v-model="headerStore.drawer"
          title="I am the title"
          :with-header="false"
        >
          <Link
            href="#about"
            :active="0"
            :text="languageStore.text.about"
            :clickFunction="() => headerStore.changeHeader(0)"
            :isMobile="true"
          />
          <Link
            href="#resume"
            :active="1"
            :text="languageStore.text.resume"
            :clickFunction="() => headerStore.changeHeader(1)"
            :isMobile="true"
          />
          <Link
            href="#project"
            :active="2"
            :text="languageStore.text.project"
            :clickFunction="() => headerStore.changeHeader(2)"
            :isMobile="true"
          />
          <Link
            href="#contact"
            :active="3"
            :text="languageStore.text.contact"
            :clickFunction="() => headerStore.changeHeader(3)"
            :isMobile="true"
          />
        </el-drawer>
      </div>
      <div class="header_right">
        <Link
          href="https://www.shanny.wang/react"
          text="To React"
          position="right"
          target="_blank"
        />
        <Link
          :text="languageStore.lang === 'zh-cn' ? '中' : 'EN'"
          position="right"
          :clickFunction="languageStore.toggleLang"
          :isMobile="true"
        />
        <!-- <Link
          :isIcon="true"
          :icon="state === 'dark' ? Moon : Sunny"
          position="right"
          :clickFunction="headerStore.toggleTheme"
        /> -->
      </div>
    </div>
  </el-affix>
</template>
<style scoped lang="scss">
.menu_icon {
  padding: 0 0.5rem;
  color: var(--my-white);
  font-size: 1.4rem;
}

.header-group {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: var(--my-header_bg);
  border-bottom: 0.1rem solid var(--my-header_border_bottom);
  width: 100vw;
  height: 6vh;
  a {
    padding: 0 0.5rem;
  }
}
</style>
